// Todo el texto que aparece dentro de las demos de Conceptos, en un solo sitio.
// Las demos son contenido de la web, así que se traducen como el resto.

export const TXT = {
  es: {
    // comunes
    scroll: 'scroll ↓',
    arrastra: 'arrastra →',
    mueveCursor: 'mueve el cursor',
    // scroll
    inicio: 'Inicio', seccion: 'Sección', final: 'Final',
    saltoSeco: 'salto seco', conInercia: 'con inercia',
    tresCapas: 'Tres capas,', tresVelocidades: 'tres velocidades',
    uno: 'uno', dos: 'dos', tres: 'tres', cuatro: 'cuatro',
    cssPuro: 'tu navegador lo hace en CSS puro',
    necesitaJs: 'tu navegador aún necesita JS para esto',
    bloque: 'Bloque',
    bajaParaVer: 'baja para verlas aparecer',
    apareceAlEntrar: 'Aparece al entrar',
    meQuedoAqui: 'Me quedo aquí',
    contenido: 'Contenido',
    scrollMueve: 'scroll ↓ mueve →',
    pasaParaParar: 'pasa el cursor para pararla',
    story: ['La figura empieza pequeña', 'Crece con el scroll', 'Y termina girada'],
    portada: 'Portada', detalle: 'Detalle',
    cambiarVista: 'cambiar de vista',
    conViewTransitions: 'con View Transitions', sinSoporteNativo: 'sin soporte nativo',
    // puntero
    acercate: 'acércate', botonTeBusca: 'el botón te busca',
    circuloTarde: 'el círculo llega tarde a propósito',
    meGusta: 'me gusta', meGustaOk: 'me gusta ✓',
    hoverPulsaSuelta: 'pasa por encima, pulsa, suelta',
    invertido: 'INVERTIDO', pasaleEncima: 'pásale por encima',
    luzTeSigue: 'la luz te sigue',
    // estética
    cristal: 'Cristal', desenfoca: 'desenfoca lo que tiene detrás',
    hundido: 'hundido', enRelieve: 'en relieve', pulsaHundir: 'pulsa para hundirlo',
    forma: 'forma', poligono: 'polígono', circulo: 'círculo', flecha: 'flecha',
    abierto: 'abierto',
    interpola: 'el navegador interpola los dos estados',
    transicionNormal: 'sin soporte: transición CSS normal',
    construyendo: 'construyendo Vibeset',
    volverCargar: 'volver a cargar', cargando: 'cargando…',
    palabraCinetica: 'movimiento', otraVez: 'otra vez',
    conGrano: 'con grano', plano: 'plano', cambiar: 'cambiar',
    contenidoListo: 'Contenido listo',
    // rendimiento
    transformGpu: 'transform · la compone la GPU',
    marginRecalcula: 'margin-left · recalcula la página',
    mismoMovimiento: 'se mueven igual; una cuesta un fotograma y la otra, la maquetación entera',
    animar: 'animar',
    medidoAhora: 'medido ahora mismo en esta página',
    buenoLcp: 'bueno: menos de 2,5 s', buenoCls: 'bueno: menos de 0,1',
    pidesMenos: 'pides menos movimiento', aceptasMovimiento: 'aceptas el movimiento',
    leidoSistema: 'leído de tu sistema, no de un botón de aquí',
    tuNavegadorTrae: 'lo que trae tu navegador ahora mismo',
    seDegrada: 'lo que falte, se degrada sin romperse',
    movil: 'móvil', tableta: 'tableta', escritorio: 'escritorio',
    bajaCadaFoto: 'baja: cada foto se pide al acercarse',
    foto: 'foto', cargada: 'cargada', esperando: 'esperando',
    escribeDeprisa: 'escribe aquí deprisa…',
    bruto: 'bruto',
    debounceThrottle: 'debounce espera a que pares; throttle deja pasar uno cada 400 ms',
    unFotograma: 'un fotograma por refresco de tu pantalla',
    // css moderno
    contenedorMide: (px) => `el contenedor mide ${px}px · a partir de 260 se parte en dos columnas`,
    unaLineaCss: 'una sola línea de CSS: clamp(.9rem, 7cqi, 2.2rem)',
    aceptoCondiciones: 'acepto las condiciones', continuar: 'continuar', marcalo: 'márcalo',
    colorGris: 'color gris', colorIndigo: 'color índigo', colorVerde: 'color verde',
    ganaUltima: 'gana la última capa',
    mismaEspecificidad: 'las tres reglas tienen la misma especificidad: decide el orden de las capas',
    subgridCortas: [
      { t: 'Corto', d: 'Una línea.' },
      { t: 'Un título bastante más largo', d: 'Dos líneas de texto para desnivelar la tarjeta.' },
      { t: 'Medio', d: 'Otra descripción.' },
    ],
    subgridSi: 'sí', subgridNo: 'no',
    empiezaIzquierda: 'empieza por la izquierda',
    direccion: 'dirección',
    bordeCambia: 'el borde cambia de lado sin tocar el CSS',
  },

  en: {
    scroll: 'scroll ↓',
    arrastra: 'drag →',
    mueveCursor: 'move the pointer',
    inicio: 'Start', seccion: 'Section', final: 'End',
    saltoSeco: 'hard jump', conInercia: 'with inertia',
    tresCapas: 'Three layers,', tresVelocidades: 'three speeds',
    uno: 'one', dos: 'two', tres: 'three', cuatro: 'four',
    cssPuro: 'your browser does this in pure CSS',
    necesitaJs: 'your browser still needs JS for this',
    bloque: 'Block',
    bajaParaVer: 'scroll to watch them appear',
    apareceAlEntrar: 'Appears on entry',
    meQuedoAqui: 'I stay right here',
    contenido: 'Content',
    scrollMueve: 'scroll ↓ moves →',
    pasaParaParar: 'hover to pause it',
    story: ['The shape starts small', 'It grows with the scroll', 'And ends up rotated'],
    portada: 'Home', detalle: 'Detail',
    cambiarVista: 'switch view',
    conViewTransitions: 'with View Transitions', sinSoporteNativo: 'no native support',
    acercate: 'come closer', botonTeBusca: 'the button chases you',
    circuloTarde: 'the circle lags behind on purpose',
    meGusta: 'like', meGustaOk: 'liked ✓',
    hoverPulsaSuelta: 'hover, press, release',
    invertido: 'INVERTED', pasaleEncima: 'move over it',
    luzTeSigue: 'the light follows you',
    cristal: 'Glass', desenfoca: 'blurs whatever sits behind it',
    hundido: 'pressed in', enRelieve: 'raised', pulsaHundir: 'press to sink it',
    forma: 'shape', poligono: 'polygon', circulo: 'circle', flecha: 'arrow',
    abierto: 'open',
    interpola: 'the browser interpolates both states',
    transicionNormal: 'no support: plain CSS transition',
    construyendo: 'building Vibeset',
    volverCargar: 'load it again', cargando: 'loading…',
    palabraCinetica: 'movement', otraVez: 'again',
    conGrano: 'with grain', plano: 'flat', cambiar: 'toggle',
    contenidoListo: 'Content ready',
    transformGpu: 'transform · composited by the GPU',
    marginRecalcula: 'margin-left · relayouts the page',
    mismoMovimiento: 'same movement; one costs a frame, the other the whole layout',
    animar: 'animate',
    medidoAhora: 'measured right now on this page',
    buenoLcp: 'good: under 2.5 s', buenoCls: 'good: under 0.1',
    pidesMenos: 'you asked for less motion', aceptasMovimiento: 'you accept motion',
    leidoSistema: 'read from your system, not from a button here',
    tuNavegadorTrae: 'what your browser ships right now',
    seDegrada: 'whatever is missing degrades without breaking',
    movil: 'phone', tableta: 'tablet', escritorio: 'desktop',
    bajaCadaFoto: 'scroll: each photo is fetched as it comes close',
    foto: 'photo', cargada: 'loaded', esperando: 'waiting',
    escribeDeprisa: 'type in here, fast…',
    bruto: 'raw',
    debounceThrottle: 'debounce waits until you stop; throttle lets one through every 400 ms',
    unFotograma: 'one frame per screen refresh',
    contenedorMide: (px) => `the container is ${px}px · past 260 it splits in two columns`,
    unaLineaCss: 'one line of CSS: clamp(.9rem, 7cqi, 2.2rem)',
    aceptoCondiciones: 'I accept the terms', continuar: 'continue', marcalo: 'tick it',
    colorGris: 'grey text', colorIndigo: 'indigo text', colorVerde: 'green text',
    ganaUltima: 'the last layer wins',
    mismaEspecificidad: 'all three rules have the same specificity: layer order decides',
    subgridCortas: [
      { t: 'Short', d: 'One line.' },
      { t: 'A noticeably longer title', d: 'Two lines of text to knock the card out of line.' },
      { t: 'Medium', d: 'Another description.' },
    ],
    subgridSi: 'on', subgridNo: 'off',
    empiezaIzquierda: 'starts from the left',
    direccion: 'direction',
    bordeCambia: 'the border swaps sides without touching the CSS',
  },
}

export const textoDe = (lang) => TXT[lang] ?? TXT.es
